name: Build (reusable workflow)
on: workflow_call

jobs:
  build:
    name: Reusable Build Workflow
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: |
            8
            17

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          # Avoid caching generated artifacts
          path: |
            ~/.m2/repository/*
            !~/.m2/repository/com/github/cowwoc/pouch
          key: ${{ runner.OS }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.OS }}-maven-

      # Maven command-line options:
      # --batch-mode: recommended in CI to inform maven to not run in interactive mode (less logs)
      # -V: strongly recommended in CI, will display the JDK and Maven versions in use.
      #      Very useful to be quickly sure the selected versions were the ones you think.
      # -Dsurefire.useFile=false : useful in CI. Displays test errors in the logs directly (instead of
      #                            having to crawl the workspace files to see the cause).
      # -e : Display stack-traces on failure
      - name: Build
        run: ./mvnw install --batch-mode -V "-Dsurefire.useFile=false" -e